### ISSUE TITLE
Does aws-alb-ingress-controller support setting health check timeouts? 

### ISSUE THREAD

**Issue by drop-harsh** [kubernetes-sigs/aws-alb-ingress-controller#747] opened 2018-11-22 19:58 UTC
I have been trying to set health check related timeouts in my ingress configuration:
```
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 5
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 2
    alb.ingress.kubernetes.io/healthy-threshold-count: 5
    alb.ingress.kubernetes.io/unhealthy-threshold-count: 2
```

But when ALB is created it doesnt seem to override any of the above timeouts? 

I'm on `v1.0.0` of aws-alb-ingress-controller. I was following logs and even there I didnt see any of those timeout config while target group creation

**Comment by krzyho** [comment] 2018-11-23 10:45
I have a similar issue.

Whenever I use above annotations the alb-ingress-controller just ignores the ingress and is not creating proper AWS Load Balancer and Target Group.

Also, setting these annotations on the Service does not take any effect.

**Comment by kumud-pe** [comment] 2018-11-23 13:48
Facing the same issue. If I use these annotations ALB is not getting created at all.

**Comment by kumud-pe** [comment] 2018-11-23 14:00
I guess the issue is with passing them as integers. If we pass them as strings it works. Looks like it was documented incorrectly.

**Comment by drop-harsh** [comment] 2018-11-23 15:59
Yeah passing them as strings seems to work

**Comment by M00nF1sh** [comment] 2018-11-27 01:12
Sorry for the late reply.

Yes, these annotations can only be strings. and boolean/integers must be quoted(otherwise, other annotations will be lost as well, i think kubectl should be improved to give error or warning for such case).

I'll update the docs today, sorry for the trouble caused

**Comment by M00nF1sh** [comment] 2018-11-27 02:12
closing this since docs have been updated 😄

**Closed by M00nF1sh** 2018-11-27 02:12 UTC
