### ISSUE TITLE
EKS worker nodes failing to register as ALB target nodes

### ISSUE THREAD

**Issue by brianbakeratx** [kubernetes-sigs/aws-alb-ingress-controller#446] opened 2018-07-05 16:38 UTC
I have created an EKS cluster and added worker nodes using [these instructions](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html) and the referenced CloudFormation template.

The alb-ingress-controller is logging an error event when attempting to register the worker nodes:

I0705 16:08:55.229718       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: ec2/DescribeInstances, Payload: {  InstanceIds: ["i-073xxx","i-0b8xxx","i-0eexxx"]}
I0705 16:08:55.345216       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: ec2/ModifyInstanceAttribute, Payload: {  Groups: ["sg-xxx","sg-yyy"],  InstanceId: "i-0b8xxx"}
E0705 16:08:55.381642       1 session.go:44] [ALB-INGRESS] [session] [ERROR]: Failed request: ec2/ModifyInstanceAttribute, Payload: {  Groups: ["sg-xxx","sg-yyy"],  InstanceId: "i-0b8xxx"}, Error: InvalidInstanceID: There are multiple interfaces attached to instance 'i-0b8xxx'. Please specify an interface ID for the operation instead.

The worker nodes are spread across 3 private subnets, each in a different AZ.
It's odd that the CF template is creating a public DNS name and IP for each node as well as 2 network interfaces.  The worker nodes on our Kops managed clusters do not have multiple network interfaces and the alb-ingress-controller is registering those nodes successfully.

Does anyone know of a workaround for registering a target node with multiple nics?

**Comment by auswells** [comment] 2018-07-06 15:20
Also running into this same issue with EKS

**Comment by bigkraig** [comment] 2018-07-11 01:11
I think this is a duplicate of #343. I'm working on support for this in #449 if you would like to test that out and see if it resolves your issues. There is some more work to do in there because as it is, you can not change the annotation from `instance` to `pod` or back without removing/creating the entire ingress.

**Closed** 2018-07-11 20:41 UTC

**Comment by cjbottaro** [comment] 2018-07-14 18:53
Hi @bigkraig, this seems to be an issue for me still using `quay.io/coreos/alb-ingress-controller:1.0-beta.3`.

I had a 2 node cluster, created an ingress, and the alb ingress controller correctly made target groups with the two instances.

Then I added a 3rd node to the cluster and the ingress controller did not add the instance to the target group.

Nothing in the logs except:
```
I0714 18:44:26.360847       1 alb-controller.go:153] [ALB-INGRESS] [controller] [INFO]: Ingress update being attempted. (Forced from no event seen in 60 seconds).
```

Forgot to mention my service is `NodePort` and I'm using the `alb.ingress.kubernetes.io/target-type: pod` annotation.

Thanks for the help!

**Comment by bigkraig** [comment] 2018-07-14 21:48
With the `target-type: pod`  annotation it should only add the pods to the TG, so adding/removing nodes shouldn't change things, only adding/removing pods. LMK!

**Comment by cjbottaro** [comment] 2018-07-15 05:30
My service only has 1 pod running, but there are are two EC2 instances in my target group.

```
$ kubectl get all -l app=sa-web
NAME                          READY     STATUS    RESTARTS   AGE
pod/sa-web-68bc5f44f4-9k55h   1/1       Running   0          1d

NAME             TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/sa-web   NodePort   172.20.57.14   <none>        80:31056/TCP   1d

NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sa-web   1         1         1            1           1d

NAME                                DESIRED   CURRENT   READY     AGE
replicaset.apps/sa-web-68bc5f44f4   1         1         1         1d
replicaset.apps/sa-web-6c57549584   0         0         0         1d
```

But then my target group has two instances, despite only 1 pod running, and 3 nodes in the cluster:
http://storage.stochasticbytes.com.s3.amazonaws.com/k4nag8pD.png

I'm confused.

**Comment by bigkraig** [comment] 2018-07-16 17:12
If you are using pod targets you would see IPs rather than instance IDs in your screenshot. I fixed a bug after the beta.3 image that allows you to switch back and forth between the types, so either upgrade to the latest image `e8035f4 ` or delete/recreate the ingress.

**Comment by spacez320** [comment] 2018-07-28 18:45
I'm encountering the problem referenced in the issue opener, using `1.0-beta.4` on EKS.

Upon registering the ingress:

```
I0728 18:42:31.100289       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"example2", Name:"nginx-ingress", UID:"f750787e-9295-11e8-866f-06cb9ba7be6a", APIVersion:"extensions", ResourceVersion:"6385418", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error adding targets to target group c551063c-30000-HTTP-36b6499: InvalidInstanceID: There are multiple interfaces attached to instance 'i-09cf66774d18752d2'. Please specify an interface ID for the operation instead.                                                                                                                                                    
        status code: 400, request id: befc49a5-36b7-4f32-837c-77357819e763
I0728 18:42:31.207792       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: ec2/DescribeInstances, Payload: {  InstanceIds: ["i-007197a4cadae8595","i-09cf66774d18752d2"]}                                                                                                                                          
I0728 18:42:31.268899       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: ec2/ModifyInstanceAttribute, Payload: {  Groups: ["sg-81dba8f0","sg-fc2f088c"],  InstanceId: "i-09cf66774d18752d2"}                                                                                                                     
E0728 18:42:31.314729       1 session.go:44] [ALB-INGRESS] [session] [ERROR]: Failed request: ec2/ModifyInstanceAttribute, Payload: {  Groups: ["sg-81dba8f0","sg-fc2f088c"],  InstanceId: "i-09cf66774d18752d2"}, Error: InvalidInstanceID: There are multiple interfaces attached to instance 'i-09cf66774d18752d2'. Please specify an interface ID for the operation instead.
E0728 18:42:31.314751       1 session.go:44] [ALB-INGRESS] [session] [ERROR]:   status code: 400, request id: b0956f8b-6bd5-4010-a7a2-4cd8be593fd5
E0728 18:42:31.314864       1 albingress.go:264] [ALB-INGRESS] [example2/nginx-ingress] [ERROR]: Failed to reconcile state on this ingress
E0728 18:42:31.314879       1 albingress.go:266] [ALB-INGRESS] [example2/nginx-ingress] [ERROR]:  - Failed TargetGroup modification. Unable to add targets: InvalidInstanceID: There are multiple interfaces attached to instance 'i-09cf66774d18752d2'. Please specify an interface ID for the operation instead.            
E0728 18:42:31.314909       1 albingress.go:266] [ALB-INGRESS] [example2/nginx-ingress] [ERROR]:        status code: 400, request id: befc49a5-36b7-4f32-837c-77357819e763                                                                                                                                                    
E0728 18:42:31.314937       1 albingress.go:266] [ALB-INGRESS] [example2/nginx-ingress] [ERROR]:  - Failed TargetGroup modification. Unable to add targets: InvalidInstanceID: There are multiple interfaces attached to instance 'i-09cf66774d18752d2'. Please specify an interface ID for the operation instead.            
E0728 18:42:31.314975       1 albingress.go:266] [ALB-INGRESS] [example2/nginx-ingress] [ERROR]:        status code: 400, request id: b0956f8b-6bd5-4010-a7a2-4cd8be593fd5                                                                                                                                                    
I0728 18:42:31.315003       1 controller.go:486] ingress backend successfully reloaded...
I0728 18:42:31.315034       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"example2", Name:"nginx-ingress", UID:"f750787e-9295-11e8-866f-06cb9ba7be6a",
```

We're using the `instance` target-type annotation. Changing to `pod` didn't seem to help the situation and presented another error that I'd be happy to share, but I don't think pods in the target group is ultimately what we want, anyway.

Happy to open a new issue.

**Comment by spacez320** [comment] 2018-08-04 16:51
Following up -- this seemed to be fixed by setting up proper network policies between Kubernetes worker EC2 instances and the ALB. I don't have details as I wasn't the one that implemented the specific fix that worked for me, but besides being a misleading error, I don't think there's anything to do here.

**Comment by cjbottaro** [comment] 2018-08-04 20:25
I'm using `target-type: pod` and everything is working for me now (using one of the beta5 images, forgot which one). 👍

**Comment by grahampfau** [comment] 2018-08-07 22:41
@spacez320 Do you think you could get more info on the policies that fixed this? I'm also hitting this same error on EKS.

**Comment by vallurupallikhetan** [comment] 2018-09-20 13:02
I an facing an issue once the deployment file is updated new pods are generated but the ip of the pod is not updated in the Target group (using EKS cluster).

**Comment by spacez320** [comment] 2018-09-20 13:32
@grahampfau Sorry, I wasn't involved in the actual diagnosis, so I don't have more details to share unfortunately.
