### ISSUE TITLE
Automatic ACM cert creation

### ISSUE THREAD

**Issue by stefansedich** [kubernetes-sigs/aws-alb-ingress-controller#1101] opened 2019-12-11 03:34 UTC
Is there any plan to support automatically creating ACM certs? with DNS validation we should be able to create a missing cert and then add the required entries in Route53. Would make for a nicer experience without having to manage the certs out-of-band in something like Terraform.

**Comment by M00nF1sh** [comment] 2019-12-14 00:43
:D planed :D

**Comment by stefansedich** [comment] 2019-12-14 01:53
:tada: @M00nF1sh would be something I would pick up but my current workload is already fairly high :crying_cat_face: when things settle down if it is still not something that is being worked on I might have a go at it.

**Comment by gmauleon** [comment] 2020-01-27 18:54
Duplicate of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1084 ?

**Closed** 2020-06-25 21:18 UTC
Labels: lifecycle/rotten
