### ISSUE TITLE
Version 1.0 status and current image version

### ISSUE THREAD

**Issue by jkemp101** [kubernetes-sigs/aws-alb-ingress-controller#375] opened 2018-05-02 13:30 UTC
I'm trying to get a handle on the current status of version 1 of the controller.  Things have been working fine with my limited production use but I need to decide if I want to roll it out to a broader set of services.

1. What version should we be running?  The Readme still says the current version is `1.0-alpha.3`, I have been running `1.0-alpha.8`.  I'd do a PR to update the Readme but I honestly don't know what version we should be testing to get ready for a 1.0 release.  Maybe if this is still alpha we should just be running `latest`?

2. The Roadmap doc points to the [Version 1 milestone](https://github.com/coreos/alb-ingress-controller/milestone/1) which has 4 issues in it but none of them seem to have any activity in the last few months.  Are they still the only issues remaining to have a V1.0 release?  I ask because this issue https://github.com/coreos/alb-ingress-controller/issues/368 seems important and should probably be added to the milestone once it is confirmed.

3. Is the project still in Alpha?  Are there near term plans to have a feature lock and get a Beta version out?

I'm just looking for some info so I can make better planning decisions.  I really want to stop using CLBs.

**Comment by gaganapplatix** [comment] 2018-05-03 21:11
We would also like to use this as well. Currently testing master which is on 1.0-alpha.9 but it is unclear when the alpha version change. Is there some release schedule or milestone around 1.0 so people can use specific tags?

**Comment by pawelprazak** [comment] 2018-05-30 16:43
Couple of questions:
- Is there any ETA for 1.0? 
- Is it actively maintained/developed? 
- Is it used in production?

I'm trying to assess whether or not my team should try to adopt it or is it not actively developed.

**Comment by bigkraig** [comment] 2018-05-31 17:55
Hey @pawelprazak, those are some pretty valid concerns.

As you can see, there has been some rough roads on the maintenance side lately. At Ticketmaster I have been focused on less Kubernetes related projects which has taken away much of my attention and @joshrosso left CoreOS and has yet not been replaced on the CoreOS/RedHat side. We did pick up another maintainer from AWS, @andrewtandoc, and he is getting up to speed and focusing on code restructure/test cases before we hit the 1.0 milestone.

Ticketmaster has been using this in production and while I don't have any official list of who else is using it, there is quite a lot of pull activity in the Quay repository.

Officially, AWS, RedHat, and Ticketmaster are committed to supporting the controller, it's just going through a bit of a transitional phase.

**Comment by ehbello** [comment] 2018-06-04 10:45
Which version does TicketMaster use in production? Which version is currently considered the most stable?

**Comment by bigkraig** [comment] 2018-06-04 16:47
@ehbello I just checked and the team is using `1e8a381`

**Comment by pawelprazak** [comment] 2018-06-06 12:52
Good to know! Would it be possible to release it then as a "named" release, like alpha 9?

**Comment by bigkraig** [comment] 2018-06-06 23:13
@pawelprazak Gonna get to this soon, right now things are getting ready for the ownership transfer to sig-aws. 

In the mean time the team was getting ready to change out to this build due to a regression: https://github.com/coreos/alb-ingress-controller/pull/384

**Comment by bigkraig** [comment] 2018-06-21 22:37
#403 fixes some TG node list regressions and I think will then be alpha 9 ready

**Comment by bigkraig** [comment] 2018-06-21 23:48
I just cut `1.0-alpha.9` 🎉

**Comment by ehbello** [comment] 2018-06-22 08:53
Great work @bigkraig! I tried the lastest build f79a092 and it seems to work flawlessly. At least I don't see any errors with the debug output enabled. Thank you!

**Comment by mvillumsen** [comment] 2018-06-25 06:54
@bigkraig Did you push the new image to the repository as well? `1.0-alpha.9` does not seem to be available at `quay.io/coreos/alb-ingress-controller` as mentioned in #412

**Comment by bigkraig** [comment] 2018-06-27 21:48
`1.0-beta.2` has been cut and has a lot of the major rework that I have wanted to get done included. I've also gone through a lot of the miscellaneous reported bugs here and verified as many as I can that they are resolved.

I have one last feature request in #405 that I think is important to get in before a 1.0 release, since it has the possibility of changing the default routing behavior (only to one that is expected, at least)

**Comment by jkemp101** [comment] 2018-06-28 11:12
@bigkraig Thanks for all of the changes/fixes.  Looks like a lot has gotten done recently. I'm wrapped up in some other projects right now but looking forward to trying 1.0.

**Comment by bigkraig** [comment] 2018-07-16 23:05
closer to the 1.0 release. the `1.0-beta.4` image supports the standard Kubernetes ELB tagging conventions for discovery, supports the AWS CNI which adds pods directly to the TG, and fixes some healthcheck problems people were experiencing.

**Closed** 2019-01-18 02:06 UTC
Labels: kind/question
