### ISSUE TITLE
Target pod gets deregistered automatically

### ISSUE THREAD

**Issue by dhawani** [kubernetes-sigs/aws-alb-ingress-controller#475] opened 2018-07-21 05:41 UTC
Version: 1.0-beta.4
I have setup https://github.com/kubernetes/charts/tree/master/stable/keycloak with following values
`
keycloak:
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:****:certificate/****
      alb.ingress.kubernetes.io/target-type: pod
    hosts:
      - abc.example.com`

post creation of ingress, I modified the ingress with integer port instead of named port. There are few problems that i want to point out:

1. The service behind the service is statefulset, which means the ip would not be immediately available. The controller is trying to register with no ips. 
`"[ALB-INGRESS] [session] [ERROR]: Failed request: elasticloadbalancing/RegisterTargets, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:*****:targetgroup/11fe95b5-31288-HTTP-287e019/99d6ebbeabb3b996"}, Error: InvalidParameter: 1 validation error(s) found."  
"[ALB-INGRESS] [session] [ERROR]: - missing required field, RegisterTargetsInput.Targets." `

2. Despite target-type:pod, the port mentioned in target creation is a NodePort
`"[ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/CreateTargetGroup, Payload: {  HealthCheckIntervalSeconds: 15,  HealthCheckPath: "/",  HealthCheckPort: "traffic-port",  HealthCheckProtocol: "HTTP",  HealthCheckTimeoutSeconds: 5,  HealthyThresholdCount: 2,  Matcher: {    HttpCode: "200"  },  Name: "11fe95b5-31288-HTTP-287e019",  Port: 31288,  Protocol: "HTTP",  TargetType: "ip",  UnhealthyThresholdCount: 2,  VpcId: "vpc-****"}" `

3. Post re-sync, all the targets are gone.
`"[ALB-INGRESS] [controller] [DEBUG]: ALB sync interval 1h0m0s elapsed; Assembly will be reattempted once lock is available.."
"[ALB-INGRESS] [keycloak/keycloak] [DEBUG]: Targets need to be changed." 
"[ALB-INGRESS] [keycloak/keycloak] [INFO]: Modifying target group targets."   
"[ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/RegisterTargets, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:***:targetgroup/11fe95b5-31288-HTTP-287e019/99d6ebbeabb3b996",  Targets: [{      Id: "*.*.*.*",      Port: 8080    }]}"   
"[ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/DeregisterTargets, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:***:targetgroup/11fe95b5-31288-HTTP-287e019/99d6ebbeabb3b996",  Targets: [{      AvailabilityZone: "us-east-1a",      Id: "*.*.*.*",      Port: 8080    }]}"   `

**Comment by blandman** [comment] 2018-07-23 16:34
I am experiencing similar behavior. I have to continually delete the alb controller to keep services from 503'ing, the target group pod pointer becomes empty upon pod redeployment. Trying to experiment with liveliness probe on alb controller, but is difficult to automate since my controller has several ingresses.

**Comment by bigkraig** [comment] 2018-07-23 16:37
Hey guys, the deregistered targets was fixed in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/461/files but I haven't made a new beta yet. I've been focused on forking the upstream ingress code into this repo which is a significant amount of backend work and is taking up most of my time.

**Comment by blandman** [comment] 2018-07-23 17:44
Thank you for the hard work on this, it surely makes the CI deployment process a breeze.

**Comment by bigkraig** [comment] 2018-07-26 22:17
@dhawani Can you check against the latest master build? A lot of the code has changed behind the scenes and it now includes the default target type parameter. Named ports are still not supported but i'd like to know how the rest of it is working for you.

**Comment by blandman** [comment] 2018-07-27 14:56
tag :fix-pod-target-az has helped out in my case, when I tried latest yesterday the `alb.ingress.kubernetes.io/backend-protocol: HTTPS` annotation was not functional.

**Comment by bigkraig** [comment] 2018-07-27 17:45
@blandman do you mind opening a separate issue for the backend-protocol issue?

**Comment by blandman** [comment] 2018-07-27 18:15
Sure thing!

**Comment by dhawani** [comment] 2018-07-28 04:11
Controller Tag Used: a6565ea
I am getting following errors:
`E0728 04:04:37.465837       1 albingress.go:297] keycloak/keycloak:  - Failed TargetGroup creation: InvalidParameter: 1 validation error(s) found.
E0728 04:04:37.465843       1 albingress.go:297] keycloak/keycloak: - minimum field value of 1, CreateTargetGroupInput.Port.
E0728 04:04:37.465845       1 albingress.go:297] keycloak/keycloak: .
I0728 04:04:37.465841       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"keycloak", Name:"keycloak", UID:"fe7b14b2-8c1e-11e8-affc-12d4fecbab7e", APIVersion:"extensions/v1beta1", ResourceVersion:"3345474", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error creating target group 11fe95b5-keycloak-http-8a2c3: InvalidParameter: 1 validation error(s) found.
- minimum field value of 1, CreateTargetGroupInput.Port.`

**Comment by bigkraig** [comment] 2018-07-31 23:08
Can you have a look with `1.0-beta.5`? It's got the latest pod target-type work in there, including fixes for managed SG

**Comment by toshipp** [comment] 2018-08-07 01:20
I use 1.0-beta.5, the issue is no longer appeared. Thanks!

**Comment by dhawani** [comment] 2018-08-07 01:43
@bigkraig I am still getting the same error.

**Comment by dhawani** [comment] 2018-08-07 01:48
@bigkraig I think the bug is now that service port cannot be named ports. changed it to numeric value and got following:
`F0807 01:46:38.629047       1 albingresses.go:151] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 2072 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc000ae9f18, 0xc000ba7080)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1683760, 0x2c1cd90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg.(*TargetGroup).Reconcile(0xc000690b60, 0xc000ae9da8, 0x1, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg/targetgroup.go:180 +0x434
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg.TargetGroups.Reconcile(0xc0006dd630, 0x2, 0x2, 0xc000ae9da8, 0x2, 0x2, 0xc0005d0578, 0x1, 0x1)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg/targetgroups.go:59 +0x85
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc000809760, 0xc000ae9e68, 0xc00067c058, 0xc00053e960, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:351 +0x413
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc0000c3e00, 0xc000948ea8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:288 +0x10b
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad3100, 0xc000023a40, 0x2, 0x0, 0x1, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:141 +0xb8
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc0000239e0, 0xc00027efc0, 0xc000ba7080)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc0001aa840)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:192 +0x3ff
main.main()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 5 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c339e0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 18 [syscall, 6 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 30 [runnable]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc0000388c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7febee133f00, 0x72, 0xc00020e870)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0003bca18, 0x72, 0xffffffffffffff00, 0x1ab3d00, 0x2bd44f0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0003bca18, 0xc0007b0000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0003bca00, 0xc0007b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0003bca00, 0xc0007b0000, 0x8000, 0x8000, 0x408a0b, 0xc00002e000, 0x16a92e0)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000d4018, 0xc0007b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc0002120c0, 0x1ab2420, 0xc0000d4018, 0x5, 0xc0000d4018, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc00006aa80, 0x1965517, 0xc00006aba0, 0xc00017ce00)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc00006aa80, 0xc00035c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc000088540, 0xc0003302d8, 0x9, 0x9, 0xc00017ce00, 0xc00020ec58, 0xc00020ec70)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x1ab0b40, 0xc000088540, 0xc0003302d8, 0x9, 0x9, 0x9, 0xc00020ecf8, 0x8057cb, 0xc000ba52c0)
	/home/travis/.gimme/versions/go/src/io/io.go:310 +0x88
io.ReadFull(0x1ab0b40, 0xc000088540, 0xc0003302d8, 0x9, 0x9, 0xc00020ed28, 0x8056dd, 0xc00020efb8)
	/home/travis/.gimme/versions/go/src/io/io.go:329 +0x58
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.readFrameHeader(0xc0003302d8, 0x9, 0x9, 0x1ab0b40, 0xc000088540, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0003302a0, 0xc0007e3770, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00020efb8, 0x1964478, 0xc000478fb8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/transport.go:1616 +0x9e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000fe000)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingres`

**Comment by bigkraig** [comment] 2018-08-07 16:19
@dhawani which version is that with? did you see https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/529?

**Comment by dhawani** [comment] 2018-08-07 16:56
1.0-beta.5

@bigkraig, was not able to check #529 as now named port in service have stopped working. 

Steps to reproduce:
1. Create service with name port
2. Create ingress with numeric port (type : ip)
3. Observe alb controller logs. You should get error creating target group
4. Edit service and replace port with numeric port
5. Observe alb controller logs. You should get panic error.

**Comment by bigkraig** [comment] 2018-08-08 17:50
@dhawani named ports in services should have never worked until #529 though?

**Comment by bigkraig** [comment] 2018-08-13 20:56
gonna close this one out and if there are new issues in 1.0-beta.6 please open up an issue with the info. this one has taken a few turns since it was first created.

**Closed by bigkraig** 2018-08-13 20:56 UTC
