### ISSUE TITLE
One ALB for all ingress

### ISSUE THREAD

**Issue by ddiawara** [kubernetes-sigs/aws-alb-ingress-controller#1265] opened 2020-05-13 22:03 UTC
Hello, everybody, I have a little problem.
In my EKS cluster, each ingress I create automatically creates an ALB, I want to move all my traffic to a single ALB.

**Comment by adw1n** [comment] 2020-05-14 21:13
Duplicate of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/688

**Comment by astrived** [comment] 2020-05-15 17:13
Like @adw1n pointed this is duplicate of #688 please tag yourself to that issue.

**Closed by astrived** 2020-05-15 17:13 UTC
